server:
  servlet:
    session:
      cookie:
        name: JSESSIONID


spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:shboard-test;MODE=Mysql

  h2:
    console:
      enabled: true

  session:
    store-type: redis
    redis:
      namespace: shboard:session


  data:
    redis:
      host: localhost
      password: 1234
      port: 6379
    web:
      pageable:
        default-page-size: 10

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
